<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <RootNamespace>Obligatorisk_opgave</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Obligatorisk opgave.Infrastructure\Obligatorisk opgave.Infrastructure.csproj" />
      <ProjectReference Include="..\Obligatorisk.opgave.Domain\Obligatorisk.opgave.Domain.csproj" />
    </ItemGroup>

</Project>
